// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Target struct {
	Target       string `json:"target"`
	LastModified string `json:"lastModified"`
	Status       string `json:"status"`
}

type TargetInput struct {
	Target string `json:"target"`
}
